name: enable auto-merge
description: Enable auto-merge
inputs:
  pr_number:
    required: true
  merge_method:
    required: false
    default: merge
  github_token:
    required: false
  github_app_id:
    required: false
  github_app_private_key:
    required: false
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        if [ "$MERGE_METHOD" = merge ] || [ "$MERGE_METHOD" = squash ] || [ "$MERGE_METHOD" = rebase ]; then
          exit 0
        fi
        echo "::error :: inputs.merge_method must be either merge, squash, and rebase."
        exit 1
      env:
        MERGE_METHOD: ${{inputs.merge_method}}
    - uses: suzuki-shunsuke/github-token-action@350d7506222e3a0016491abe85b5c4dd475b67d1 # v0.2.1
      id: token
      with:
        github_token: ${{inputs.github_token}}
        github_app_id: ${{inputs.github_app_id}}
        github_app_private_key: ${{inputs.gh_app_private_key}}
        github_app_permissions: >-
          {
            "contents": "write",
            "pull-requests": "write"
          }
        github_app_repositories: >-
          [
            "${{github.event.repository.name}}"
          ]
    - run: gh -R "$GITHUB_REPOSITORY" pr merge --${{inputs.merge_method}} --auto --delete-branch "$PR_NUMBER"
      env:
        GITHUB_TOKEN: ${{steps.token.outputs.token}}
        PR_NUMBER: ${{inputs.pr_number}}
